# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akv < Formula
  desc "Azure Key Vault command-line interface"
  homepage "https://github.com/frostyeti/akv"
  version "0.0.0-alpha.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frostyeti/akv/releases/download/v0.0.0-alpha.1/akv-darwin-amd64-v0.0.0-alpha.1.tar.gz"
      sha256 "0b95b83cf0a5e35b276bce525f0f2638d3b55e6b936f9c3dfa3ae34a102c60a9"

      define_method(:install) do
        bin.install "akv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frostyeti/akv/releases/download/v0.0.0-alpha.1/akv-darwin-arm64-v0.0.0-alpha.1.tar.gz"
      sha256 "c6b4d31ba896f3984e35519b8528c845adceb18e6435248d040cf83877d919d3"

      define_method(:install) do
        bin.install "akv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frostyeti/akv/releases/download/v0.0.0-alpha.1/akv-linux-amd64-v0.0.0-alpha.1.tar.gz"
      sha256 "71b177b5fe03723771a9f2f9d5c556595cbea95d04c6678d89a5f1512fda8f25"
      define_method(:install) do
        bin.install "akv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frostyeti/akv/releases/download/v0.0.0-alpha.1/akv-linux-arm64-v0.0.0-alpha.1.tar.gz"
      sha256 "53792347771e26af75a9c6ca0c1a7c9e353411b9067f54bc232668cf515d6a6c"
      define_method(:install) do
        bin.install "akv"
      end
    end
  end

  test do
    system "#{bin}/akv", "--version"
  end
end
