# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osv < Formula
  desc "A cli to interact with operating system vaults."
  homepage "https://github.com/frostyeti/osv"
  version "0.0.0-alpha.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frostyeti/osv/releases/download/v0.0.0-alpha.2/osv_darwin_amd64.tar.gz"
      sha256 "8cb2add0ff48570418027fabfa0ae3d450e3d48dbf0a0e8687b4f8bc66ccb667"

      define_method(:install) do
        bin.install "osv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frostyeti/osv/releases/download/v0.0.0-alpha.2/osv_darwin_arm64.tar.gz"
      sha256 "3c8b9b9b553b439e9052582f4017e82c77510da11926315177d4563f2a4f7cd8"

      define_method(:install) do
        bin.install "osv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frostyeti/osv/releases/download/v0.0.0-alpha.2/osv_linux_amd64.tar.gz"
      sha256 "cf9a17a3f1f22b75d3be3006b106f144b70ccad95fb093867cd654a85ffb53c2"
      define_method(:install) do
        bin.install "osv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frostyeti/osv/releases/download/v0.0.0-alpha.2/osv_linux_arm64.tar.gz"
      sha256 "9fd2713d5f095c60e902a0b9283de85626d3693a9c34d47cec1a78bc98a130ec"
      define_method(:install) do
        bin.install "osv"
      end
    end
  end
end
