# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osv < Formula
  desc "A cli to interact with operating system vaults."
  homepage "https://github.com/frostyeti/osv"
  version "0.0.0-alpha.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frostyeti/osv/releases/download/v0.0.0-alpha.0/osv_darwin_amd64.tar.gz"
      sha256 "26f8bf8c6b94a4d4d3b4989e21c3f73c19f2e5fbbfd07dedbe5a1421caee6e33"

      define_method(:install) do
        bin.install "osv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frostyeti/osv/releases/download/v0.0.0-alpha.0/osv_darwin_arm64.tar.gz"
      sha256 "6f3eaf79daa000217912cf0fe8ae91bf107e5179c5faa6cca201b82c7e7b5558"

      define_method(:install) do
        bin.install "osv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frostyeti/osv/releases/download/v0.0.0-alpha.0/osv_linux_amd64.tar.gz"
      sha256 "6c378c824eb8c5c666da1b968f11ceee6cc19c393108525c3aee4149bc5ffebe"
      define_method(:install) do
        bin.install "osv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frostyeti/osv/releases/download/v0.0.0-alpha.0/osv_linux_arm64.tar.gz"
      sha256 "30f909a9efe0f1d31e45420fc939d7d93f570ecbe77369f0a5444db76d3253c2"
      define_method(:install) do
        bin.install "osv"
      end
    end
  end
end
